// next.config.mjs
export default {
  images: {
    domains: [
      "marketing.uz",
      "e7.pngegg.com",
      "upload.wikimedia.org",
      "w7.pngwing.com",
      "udevs.io",
      "static.lottiefiles.com",
      "static.lottiefiles.com",
      "1000logos.net",
      "files.readme.io",
      "cdn4.iconfinder.com",
      "download.logo.wine",
      "partner.zoom.us",
      "mir-s3-cdn-cf.behance.net",
      "cdn3.iconfinder.com",
      "cdn.iconscout.com",
      "static-00.iconduck.com",
      "balsamiq.com",
      "images.g2crowd.com" ,
      "logos-world.net",
      "cdn.icon-icons.com",
      "go.dev",
      "cdn2.iconfinder.com",
      "seeklogo.com" ,
      "api.logobank.uz",
      "substackcdn.com" ,
       "i0.wp.com",
       "dostavkainfo.uz",
       "static.vecteezy.com" ,
       "png.pngtree.com",
    ], // Add any other domains you need to allow here
  },
};
